"""Add syntax column to paste table

Revision ID: 1c143ba6f576
Revises: 207e11194557
Create Date: 2026-03-29 12:26:14.358393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c143ba6f576'
down_revision: Union[str, None] = '207e11194557'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paste', sa.Column('syntax', sa.String(), server_default='plaintext', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paste', 'syntax')
    # ### end Alembic commands ###
